<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;

class LocalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('countries')->insert([
            ['iso' => 'AF', 'country_name' => 'Afghanistan', 'iso3' => 'AFG', 'numcode' => '4', 'phonecode' => '93', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'AL', 'country_name' => 'Albania', 'iso3' => 'ALB', 'numcode' => '8', 'phonecode' => '355', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'DZ', 'country_name' => 'Algeria', 'iso3' => 'DZA', 'numcode' => '12', 'phonecode' => '213', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'AS', 'country_name' => 'American Samoa', 'iso3' => 'ASM', 'numcode' => '16', 'phonecode' => '1684', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'AD', 'country_name' => 'Andorra', 'iso3' => 'AND', 'numcode' => '20', 'phonecode' => '376', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'AO', 'country_name' => 'Angola', 'iso3' => 'AGO', 'numcode' => '24', 'phonecode' => '244', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'AI', 'country_name' => 'Anguilla', 'iso3' => 'AIA', 'numcode' => '660', 'phonecode' => '1264', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'AG', 'country_name' => 'Antigua and Barbuda', 'iso3' => 'ATG', 'numcode' => '28', 'phonecode' => '1268', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'AR', 'country_name' => 'Argentina', 'iso3' => 'ARG', 'numcode' => '32', 'phonecode' => '54', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'AM', 'country_name' => 'Armenia', 'iso3' => 'ARM', 'numcode' => '51', 'phonecode' => '374', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'AW', 'country_name' => 'Aruba', 'iso3' => 'ABW', 'numcode' => '533', 'phonecode' => '297', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'AU', 'country_name' => 'Australia', 'iso3' => 'AUS', 'numcode' => '36', 'phonecode' => '61', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'AT', 'country_name' => 'Austria', 'iso3' => 'AUT', 'numcode' => '40', 'phonecode' => '43', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'AZ', 'country_name' => 'Azerbaijan', 'iso3' => 'AZE', 'numcode' => '31', 'phonecode' => '994', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'BS', 'country_name' => 'Bahamas', 'iso3' => 'BHS', 'numcode' => '44', 'phonecode' => '1242', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'BH', 'country_name' => 'Bahrain', 'iso3' => 'BHR', 'numcode' => '48', 'phonecode' => '973', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'BD', 'country_name' => 'Bangladesh', 'iso3' => 'BGD', 'numcode' => '50', 'phonecode' => '880', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'BB', 'country_name' => 'Barbados', 'iso3' => 'BRB', 'numcode' => '52', 'phonecode' => '1246', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'BY', 'country_name' => 'Belarus', 'iso3' => 'BLR', 'numcode' => '112', 'phonecode' => '375', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'BE', 'country_name' => 'Belgium', 'iso3' => 'BEL', 'numcode' => '56', 'phonecode' => '32', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'BZ', 'country_name' => 'Belize', 'iso3' => 'BLZ', 'numcode' => '84', 'phonecode' => '501', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'BJ', 'country_name' => 'Benin', 'iso3' => 'BEN', 'numcode' => '204', 'phonecode' => '229', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'BM', 'country_name' => 'Bermuda', 'iso3' => 'BMU', 'numcode' => '60', 'phonecode' => '1441', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'BT', 'country_name' => 'Bhutan', 'iso3' => 'BTN', 'numcode' => '64', 'phonecode' => '975', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'BO', 'country_name' => 'Bolivia', 'iso3' => 'BOL', 'numcode' => '68', 'phonecode' => '591', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'BA', 'country_name' => 'Bosnia and Herzegovina', 'iso3' => 'BIH', 'numcode' => '70', 'phonecode' => '387', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'BW', 'country_name' => 'Botswana', 'iso3' => 'BWA', 'numcode' => '72', 'phonecode' => '267', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'BR', 'country_name' => 'Brazil', 'iso3' => 'BRA', 'numcode' => '76', 'phonecode' => '55', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'IO', 'country_name' => 'British Indian Ocean Territory', 'iso3' => NULL,'numcode' => NULL,'phonecode' => '246', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'BN', 'country_name' => 'Brunei Darussalam', 'iso3' => 'BRN', 'numcode' => '96', 'phonecode' => '673', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'BG', 'country_name' => 'Bulgaria', 'iso3' => 'BGR', 'numcode' => '100', 'phonecode' => '359', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'BF', 'country_name' => 'Burkina Faso', 'iso3' => 'BFA', 'numcode' => '854', 'phonecode' => '226', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'BI', 'country_name' => 'Burundi', 'iso3' => 'BDI', 'numcode' => '108', 'phonecode' => '257', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'KH', 'country_name' => 'Cambodia', 'iso3' => 'KHM', 'numcode' => '116', 'phonecode' => '855', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'CM', 'country_name' => 'Cameroon', 'iso3' => 'CMR', 'numcode' => '120', 'phonecode' => '237', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'CA', 'country_name' => 'Canada', 'iso3' => 'CAN', 'numcode' => '124', 'phonecode' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'CV', 'country_name' => 'Cape Verde', 'iso3' => 'CPV', 'numcode' => '132', 'phonecode' => '238', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'KY', 'country_name' => 'Cayman Islands', 'iso3' => 'CYM', 'numcode' => '136', 'phonecode' => '1345', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'CF', 'country_name' => 'Central African Republic', 'iso3' => 'CAF', 'numcode' => '140', 'phonecode' => '236', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'TD', 'country_name' => 'Chad', 'iso3' => 'TCD', 'numcode' => '148', 'phonecode' => '235', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'CL', 'country_name' => 'Chile', 'iso3' => 'CHL', 'numcode' => '152', 'phonecode' => '56', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'CN', 'country_name' => 'China', 'iso3' => 'CHN', 'numcode' => '156', 'phonecode' => '86', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'CX', 'country_name' => 'Christmas Island', 'iso3' => NULL,'numcode' => NULL,'phonecode' => '61', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'CC', 'country_name' => 'Cocos (Keeling) Islands', 'iso3' => NULL,'numcode' => NULL,'phonecode' => '672', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'CO', 'country_name' => 'Colombia', 'iso3' => 'COL', 'numcode' => '170', 'phonecode' => '57', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'KM', 'country_name' => 'Comoros', 'iso3' => 'COM', 'numcode' => '174', 'phonecode' => '269', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'CG', 'country_name' => 'Congo', 'iso3' => 'COG', 'numcode' => '178', 'phonecode' => '243', 'created_at' => now(), 'updated_at' => now()],
            // ['iso' => 'CD', 'country_name' => 'Congo, the Democratic Republic of the', 'iso3' => 'COD', 'numcode' => '180', 'phonecode' => '242', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'CK', 'country_name' => 'Cook Islands', 'iso3' => 'COK', 'numcode' => '184', 'phonecode' => '682', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'CR', 'country_name' => 'Costa Rica', 'iso3' => 'CRI', 'numcode' => '188', 'phonecode' => '506', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'CI', 'country_name' => 'Cote D\'Ivoire', 'iso3' => 'CIV', 'numcode' => '384', 'phonecode' => '225', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'HR', 'country_name' => 'Croatia', 'iso3' => 'HRV', 'numcode' => '191', 'phonecode' => '385', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'CU', 'country_name' => 'Cuba', 'iso3' => 'CUB', 'numcode' => '192', 'phonecode' => '53', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'CY', 'country_name' => 'Cyprus', 'iso3' => 'CYP', 'numcode' => '196', 'phonecode' => '357', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'CZ', 'country_name' => 'Czech Republic', 'iso3' => 'CZE', 'numcode' => '203', 'phonecode' => '420', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'DK', 'country_name' => 'Denmark', 'iso3' => 'DNK', 'numcode' => '208', 'phonecode' => '45', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'DJ', 'country_name' => 'Djibouti', 'iso3' => 'DJI', 'numcode' => '262', 'phonecode' => '253', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'DM', 'country_name' => 'Dominica', 'iso3' => 'DMA', 'numcode' => '212', 'phonecode' => '1767', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'DO', 'country_name' => 'Dominican Republic', 'iso3' => 'DOM', 'numcode' => '214', 'phonecode' => '1809', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'EC', 'country_name' => 'Ecuador', 'iso3' => 'ECU', 'numcode' => '218', 'phonecode' => '593', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'EG', 'country_name' => 'Egypt', 'iso3' => 'EGY', 'numcode' => '818', 'phonecode' => '20', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'SV', 'country_name' => 'El Salvador', 'iso3' => 'SLV', 'numcode' => '222', 'phonecode' => '503', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'GQ', 'country_name' => 'Equatorial Guinea', 'iso3' => 'GNQ', 'numcode' => '226', 'phonecode' => '240', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'ER', 'country_name' => 'Eritrea', 'iso3' => 'ERI', 'numcode' => '232', 'phonecode' => '291', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'EE', 'country_name' => 'Estonia', 'iso3' => 'EST', 'numcode' => '233', 'phonecode' => '372', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'ET', 'country_name' => 'Ethiopia', 'iso3' => 'ETH', 'numcode' => '231', 'phonecode' => '251', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'FK', 'country_name' => 'Falkland Islands (Malvinas)', 'iso3' => 'FLK', 'numcode' => '238', 'phonecode' => '500', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'FO', 'country_name' => 'Faroe Islands', 'iso3' => 'FRO', 'numcode' => '234', 'phonecode' => '298', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'FJ', 'country_name' => 'Fiji', 'iso3' => 'FJI', 'numcode' => '242', 'phonecode' => '679', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'FI', 'country_name' => 'Finland', 'iso3' => 'FIN', 'numcode' => '246', 'phonecode' => '358', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'FR', 'country_name' => 'France', 'iso3' => 'FRA', 'numcode' => '250', 'phonecode' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'GF', 'country_name' => 'French Guiana', 'iso3' => 'GUF', 'numcode' => '254', 'phonecode' => '594', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'PF', 'country_name' => 'French Polynesia', 'iso3' => 'PYF', 'numcode' => '258', 'phonecode' => '689', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'GA', 'country_name' => 'Gabon', 'iso3' => 'GAB', 'numcode' => '266', 'phonecode' => '241', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'GM', 'country_name' => 'Gambia', 'iso3' => 'GMB', 'numcode' => '270', 'phonecode' => '220', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'GE', 'country_name' => 'Georgia', 'iso3' => 'GEO', 'numcode' => '268', 'phonecode' => '995', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'DE', 'country_name' => 'Germany', 'iso3' => 'DEU', 'numcode' => '276', 'phonecode' => '49', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'GH', 'country_name' => 'Ghana', 'iso3' => 'GHA', 'numcode' => '288', 'phonecode' => '233', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'GI', 'country_name' => 'Gibraltar', 'iso3' => 'GIB', 'numcode' => '292', 'phonecode' => '350', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'GR', 'country_name' => 'Greece', 'iso3' => 'GRC', 'numcode' => '300', 'phonecode' => '30', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'GL', 'country_name' => 'Greenland', 'iso3' => 'GRL', 'numcode' => '304', 'phonecode' => '299', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'GD', 'country_name' => 'Grenada', 'iso3' => 'GRD', 'numcode' => '308', 'phonecode' => '1473', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'GP', 'country_name' => 'Guadeloupe', 'iso3' => 'GLP', 'numcode' => '312', 'phonecode' => '590', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'GU', 'country_name' => 'Guam', 'iso3' => 'GUM', 'numcode' => '316', 'phonecode' => '1671', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'GT', 'country_name' => 'Guatemala', 'iso3' => 'GTM', 'numcode' => '320', 'phonecode' => '502', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'GN', 'country_name' => 'Guinea', 'iso3' => 'GIN', 'numcode' => '324', 'phonecode' => '224', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'GW', 'country_name' => 'Guinea-Bissau', 'iso3' => 'GNB', 'numcode' => '624', 'phonecode' => '245', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'GY', 'country_name' => 'Guyana', 'iso3' => 'GUY', 'numcode' => '328', 'phonecode' => '592', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'HT', 'country_name' => 'Haiti', 'iso3' => 'HTI', 'numcode' => '332', 'phonecode' => '509', 'created_at' => now(), 'updated_at' => now()],
        
            ['iso' => 'VA', 'country_name' => 'Holy See (Vatican City State)', 'iso3' => 'VAT', 'numcode' => '336', 'phonecode' => '39', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'HN', 'country_name' => 'Honduras', 'iso3' => 'HND', 'numcode' => '340', 'phonecode' => '504', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'HK', 'country_name' => 'Hong Kong', 'iso3' => 'HKG', 'numcode' => '344', 'phonecode' => '852', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'HU', 'country_name' => 'Hungary', 'iso3' => 'HUN', 'numcode' => '348', 'phonecode' => '36', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'IS', 'country_name' => 'Iceland', 'iso3' => 'ISL', 'numcode' => '352', 'phonecode' => '354', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'IN', 'country_name' => 'India', 'iso3' => 'IND', 'numcode' => '356', 'phonecode' => '91', 'created_at' => now(), 'updated_at' => now()],


            // Records 100-199 (Indonesia to Spain)

            ['iso' => 'ID', 'country_name' => 'Indonesia', 'iso3' => 'IDN', 'numcode' => '360', 'phonecode' => '62', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'IR', 'country_name' => 'Iran', 'iso3' => 'IRN', 'numcode' => '364', 'phonecode' => '98', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'IQ', 'country_name' => 'Iraq', 'iso3' => 'IRQ', 'numcode' => '368', 'phonecode' => '964', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'IE', 'country_name' => 'Ireland', 'iso3' => 'IRL', 'numcode' => '372', 'phonecode' => '353', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'IL', 'country_name' => 'Israel', 'iso3' => 'ISR', 'numcode' => '376', 'phonecode' => '972', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'IT', 'country_name' => 'Italy', 'iso3' => 'ITA', 'numcode' => '380', 'phonecode' => '39', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'JM', 'country_name' => 'Jamaica', 'iso3' => 'JAM', 'numcode' => '388', 'phonecode' => '1876', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'JP', 'country_name' => 'Japan', 'iso3' => 'JPN', 'numcode' => '392', 'phonecode' => '81', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'JO', 'country_name' => 'Jordan', 'iso3' => 'JOR', 'numcode' => '400', 'phonecode' => '962', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'KZ', 'country_name' => 'Kazakhstan', 'iso3' => 'KAZ', 'numcode' => '398', 'phonecode' => '7', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'KE', 'country_name' => 'Kenya', 'iso3' => 'KEN', 'numcode' => '404', 'phonecode' => '254', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'KI', 'country_name' => 'Kiribati', 'iso3' => 'KIR', 'numcode' => '296', 'phonecode' => '686', 'created_at' => now(), 'updated_at' => now()],
            // ['iso' => 'KP', 'country_name' => 'Korea, Democratic People\'s Republic of', 'iso3' => 'PRK', 'numcode' => '408', 'phonecode' => '850', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'KR', 'country_name' => 'Korea', 'iso3' => 'KOR', 'numcode' => '410', 'phonecode' => '82', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'KW', 'country_name' => 'Kuwait', 'iso3' => 'KWT', 'numcode' => '414', 'phonecode' => '965', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'KG', 'country_name' => 'Kyrgyzstan', 'iso3' => 'KGZ', 'numcode' => '417', 'phonecode' => '996', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'LA', 'country_name' => 'Lao People\'s Democratic Republic', 'iso3' => 'LAO', 'numcode' => '418', 'phonecode' => '856', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'LV', 'country_name' => 'Latvia', 'iso3' => 'LVA', 'numcode' => '428', 'phonecode' => '371', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'LB', 'country_name' => 'Lebanon', 'iso3' => 'LBN', 'numcode' => '422', 'phonecode' => '961', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'LS', 'country_name' => 'Lesotho', 'iso3' => 'LSO', 'numcode' => '426', 'phonecode' => '266', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'LR', 'country_name' => 'Liberia', 'iso3' => 'LBR', 'numcode' => '430', 'phonecode' => '231', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'LY', 'country_name' => 'Libyan Arab Jamahiriya', 'iso3' => 'LBY', 'numcode' => '434', 'phonecode' => '218', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'LI', 'country_name' => 'Liechtenstein', 'iso3' => 'LIE', 'numcode' => '438', 'phonecode' => '423', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'LT', 'country_name' => 'Lithuania', 'iso3' => 'LTU', 'numcode' => '440', 'phonecode' => '370', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'LU', 'country_name' => 'Luxembourg', 'iso3' => 'LUX', 'numcode' => '442', 'phonecode' => '352', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'MO', 'country_name' => 'Macao', 'iso3' => 'MAC', 'numcode' => '446', 'phonecode' => '853', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'MK', 'country_name' => 'Macedonia', 'iso3' => 'MKD', 'numcode' => '807', 'phonecode' => '389', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'MG', 'country_name' => 'Madagascar', 'iso3' => 'MDG', 'numcode' => '450', 'phonecode' => '261', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'MW', 'country_name' => 'Malawi', 'iso3' => 'MWI', 'numcode' => '454', 'phonecode' => '265', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'MY', 'country_name' => 'Malaysia', 'iso3' => 'MYS', 'numcode' => '458', 'phonecode' => '60', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'MV', 'country_name' => 'Maldives', 'iso3' => 'MDV', 'numcode' => '462', 'phonecode' => '960', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'ML', 'country_name' => 'Mali', 'iso3' => 'MLI', 'numcode' => '466', 'phonecode' => '223', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'MT', 'country_name' => 'Malta', 'iso3' => 'MLT', 'numcode' => '470', 'phonecode' => '356', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'MH', 'country_name' => 'Marshall Islands', 'iso3' => 'MHL', 'numcode' => '584', 'phonecode' => '692', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'MQ', 'country_name' => 'Martinique', 'iso3' => 'MTQ', 'numcode' => '474', 'phonecode' => '596', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'MR', 'country_name' => 'Mauritania', 'iso3' => 'MRT', 'numcode' => '478', 'phonecode' => '222', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'MU', 'country_name' => 'Mauritius', 'iso3' => 'MUS', 'numcode' => '480', 'phonecode' => '230', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'YT', 'country_name' => 'Mayotte', 'iso3' => NULL,'numcode' => NULL,'phonecode' => '269', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'MX', 'country_name' => 'Mexico', 'iso3' => 'MEX', 'numcode' => '484', 'phonecode' => '52', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'FM', 'country_name' => 'Micronesia', 'iso3' => 'FSM', 'numcode' => '583', 'phonecode' => '691', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'MD', 'country_name' => 'Moldova', 'iso3' => 'MDA', 'numcode' => '498', 'phonecode' => '373', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'MC', 'country_name' => 'Monaco', 'iso3' => 'MCO', 'numcode' => '492', 'phonecode' => '377', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'MN', 'country_name' => 'Mongolia', 'iso3' => 'MNG', 'numcode' => '496', 'phonecode' => '976', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'MS', 'country_name' => 'Montserrat', 'iso3' => 'MSR', 'numcode' => '500', 'phonecode' => '1664', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'MA', 'country_name' => 'Morocco', 'iso3' => 'MAR', 'numcode' => '504', 'phonecode' => '212', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'MZ', 'country_name' => 'Mozambique', 'iso3' => 'MOZ', 'numcode' => '508', 'phonecode' => '258', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'MM', 'country_name' => 'Myanmar', 'iso3' => 'MMR', 'numcode' => '104', 'phonecode' => '95', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'NA', 'country_name' => 'Namibia', 'iso3' => 'NAM', 'numcode' => '516', 'phonecode' => '264', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'NR', 'country_name' => 'Nauru', 'iso3' => 'NRU', 'numcode' => '520', 'phonecode' => '674', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'NP', 'country_name' => 'Nepal', 'iso3' => 'NPL', 'numcode' => '524', 'phonecode' => '977', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'NL', 'country_name' => 'Netherlands', 'iso3' => 'NLD', 'numcode' => '528', 'phonecode' => '31', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'AN', 'country_name' => 'Netherlands Antilles', 'iso3' => 'ANT', 'numcode' => '530', 'phonecode' => '599', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'NC', 'country_name' => 'New Caledonia', 'iso3' => 'NCL', 'numcode' => '540', 'phonecode' => '687', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'NZ', 'country_name' => 'New Zealand', 'iso3' => 'NZL', 'numcode' => '554', 'phonecode' => '64', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'NI', 'country_name' => 'Nicaragua', 'iso3' => 'NIC', 'numcode' => '558', 'phonecode' => '505', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'NE', 'country_name' => 'Niger', 'iso3' => 'NER', 'numcode' => '562', 'phonecode' => '227', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'NG', 'country_name' => 'Nigeria', 'iso3' => 'NGA', 'numcode' => '566', 'phonecode' => '234', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'NU', 'country_name' => 'Niue', 'iso3' => 'NIU', 'numcode' => '570', 'phonecode' => '683', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'NF', 'country_name' => 'Norfolk Island', 'iso3' => 'NFK', 'numcode' => '574', 'phonecode' => '672', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'MP', 'country_name' => 'Northern Mariana Islands', 'iso3' => 'MNP', 'numcode' => '580', 'phonecode' => '1670', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'NO', 'country_name' => 'Norway', 'iso3' => 'NOR', 'numcode' => '578', 'phonecode' => '47', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'OM', 'country_name' => 'Oman', 'iso3' => 'OMN', 'numcode' => '512', 'phonecode' => '968', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'PK', 'country_name' => 'Pakistan', 'iso3' => 'PAK', 'numcode' => '586', 'phonecode' => '92', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'PW', 'country_name' => 'Palau', 'iso3' => 'PLW', 'numcode' => '585', 'phonecode' => '680', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'PS', 'country_name' => 'Palestinian Territory', 'iso3' => NULL,'numcode' => NULL,'phonecode' => '970', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'PA', 'country_name' => 'Panama', 'iso3' => 'PAN', 'numcode' => '591', 'phonecode' => '507', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'PG', 'country_name' => 'Papua New Guinea', 'iso3' => 'PNG', 'numcode' => '598', 'phonecode' => '675', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'PY', 'country_name' => 'Paraguay', 'iso3' => 'PRY', 'numcode' => '600', 'phonecode' => '595', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'PE', 'country_name' => 'Peru', 'iso3' => 'PER', 'numcode' => '604', 'phonecode' => '51', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'PH', 'country_name' => 'Philippines', 'iso3' => 'PHL', 'numcode' => '608', 'phonecode' => '63', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'PL', 'country_name' => 'Poland', 'iso3' => 'POL', 'numcode' => '616', 'phonecode' => '48', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'PT', 'country_name' => 'Portugal', 'iso3' => 'PRT', 'numcode' => '620', 'phonecode' => '351', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'PR', 'country_name' => 'Puerto Rico', 'iso3' => 'PRI', 'numcode' => '630', 'phonecode' => '1787', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'QA', 'country_name' => 'Qatar', 'iso3' => 'QAT', 'numcode' => '634', 'phonecode' => '974', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'RE', 'country_name' => 'Reunion', 'iso3' => 'REU', 'numcode' => '638', 'phonecode' => '262', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'RO', 'country_name' => 'Romania', 'iso3' => 'ROM', 'numcode' => '642', 'phonecode' => '40', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'RU', 'country_name' => 'Russian Federation', 'iso3' => 'RUS', 'numcode' => '643', 'phonecode' => '70', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'RW', 'country_name' => 'Rwanda', 'iso3' => 'RWA', 'numcode' => '646', 'phonecode' => '250', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'SH', 'country_name' => 'Saint Helena', 'iso3' => 'SHN', 'numcode' => '654', 'phonecode' => '290', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'KN', 'country_name' => 'Saint Kitts and Nevis', 'iso3' => 'KNA', 'numcode' => '659', 'phonecode' => '1869', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'LC', 'country_name' => 'Saint Lucia', 'iso3' => 'LCA', 'numcode' => '662', 'phonecode' => '1758', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'PM', 'country_name' => 'Saint Pierre and Miquelon', 'iso3' => 'SPM', 'numcode' => '666', 'phonecode' => '508', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'VC', 'country_name' => 'Saint Vincent and the Grenadines', 'iso3' => 'VCT', 'numcode' => '670', 'phonecode' => '1784', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'WS', 'country_name' => 'Samoa', 'iso3' => 'WSM', 'numcode' => '882', 'phonecode' => '684', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'SM', 'country_name' => 'San Marino', 'iso3' => 'SMR', 'numcode' => '674', 'phonecode' => '378', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'ST', 'country_name' => 'Sao Tome and Principe', 'iso3' => 'STP', 'numcode' => '678', 'phonecode' => '239', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'SA', 'country_name' => 'Saudi Arabia', 'iso3' => 'SAU', 'numcode' => '682', 'phonecode' => '966', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'SN', 'country_name' => 'Senegal', 'iso3' => 'SEN', 'numcode' => '686', 'phonecode' => '221', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'CS', 'country_name' => 'Serbia and Montenegro', 'iso3' => NULL,'numcode' => NULL,'phonecode' => '381', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'SC', 'country_name' => 'Seychelles', 'iso3' => 'SYC', 'numcode' => '690', 'phonecode' => '248', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'SL', 'country_name' => 'Sierra Leone', 'iso3' => 'SLE', 'numcode' => '694', 'phonecode' => '232', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'SG', 'country_name' => 'Singapore', 'iso3' => 'SGP', 'numcode' => '702', 'phonecode' => '65', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'SK', 'country_name' => 'Slovakia', 'iso3' => 'SVK', 'numcode' => '703', 'phonecode' => '421', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'SI', 'country_name' => 'Slovenia', 'iso3' => 'SVN', 'numcode' => '705', 'phonecode' => '386', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'SB', 'country_name' => 'Solomon Islands', 'iso3' => 'SLB', 'numcode' => '90', 'phonecode' => '677', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'SO', 'country_name' => 'Somalia', 'iso3' => 'SOM', 'numcode' => '706', 'phonecode' => '252', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'ZA', 'country_name' => 'South Africa', 'iso3' => 'ZAF', 'numcode' => '710', 'phonecode' => '27', 'created_at' => now(), 'updated_at' => now()],
    
            ['iso' => 'ES', 'country_name' => 'Spain', 'iso3' => 'ESP', 'numcode' => '724', 'phonecode' => '34', 'created_at' => now(), 'updated_at' => now()],


            // Records 200-253 (Sri Lanka to South Sudan)

            ['iso' => 'LK', 'country_name' => 'Sri Lanka', 'iso3' => 'LKA', 'numcode' => '144', 'phonecode' => '94', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'SD', 'country_name' => 'Sudan', 'iso3' => 'SDN', 'numcode' => '736', 'phonecode' => '249', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'SR', 'country_name' => 'Suriname', 'iso3' => 'SUR', 'numcode' => '740', 'phonecode' => '597', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'SJ', 'country_name' => 'Svalbard and Jan Mayen', 'iso3' => 'SJM', 'numcode' => '744', 'phonecode' => '47', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'SZ', 'country_name' => 'Swaziland', 'iso3' => 'SWZ', 'numcode' => '748', 'phonecode' => '268', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'SE', 'country_name' => 'Sweden', 'iso3' => 'SWE', 'numcode' => '752', 'phonecode' => '46', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'CH', 'country_name' => 'Switzerland', 'iso3' => 'CHE', 'numcode' => '756', 'phonecode' => '41', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'SY', 'country_name' => 'Syrian Arab Republic', 'iso3' => 'SYR', 'numcode' => '760', 'phonecode' => '963', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'TW', 'country_name' => 'Taiwan', 'iso3' => 'TWN', 'numcode' => '158', 'phonecode' => '886', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'TJ', 'country_name' => 'Tajikistan', 'iso3' => 'TJK', 'numcode' => '762', 'phonecode' => '992', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'TZ', 'country_name' => 'Tanzania', 'iso3' => 'TZA', 'numcode' => '834', 'phonecode' => '255', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'TH', 'country_name' => 'Thailand', 'iso3' => 'THA', 'numcode' => '764', 'phonecode' => '66', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'TL', 'country_name' => 'Timor-Leste', 'iso3' => NULL,'numcode' => NULL,'phonecode' => '670', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'TG', 'country_name' => 'Togo', 'iso3' => 'TGO', 'numcode' => '768', 'phonecode' => '228', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'TK', 'country_name' => 'Tokelau', 'iso3' => 'TKL', 'numcode' => '772', 'phonecode' => '690', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'TO', 'country_name' => 'Tonga', 'iso3' => 'TON', 'numcode' => '776', 'phonecode' => '676', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'TT', 'country_name' => 'Trinidad and Tobago', 'iso3' => 'TTO', 'numcode' => '780', 'phonecode' => '1868', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'TN', 'country_name' => 'Tunisia', 'iso3' => 'TUN', 'numcode' => '788', 'phonecode' => '216', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'TR', 'country_name' => 'Turkey', 'iso3' => 'TUR', 'numcode' => '792', 'phonecode' => '90', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'TM', 'country_name' => 'Turkmenistan', 'iso3' => 'TKM', 'numcode' => '795', 'phonecode' => '7370', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'TC', 'country_name' => 'Turks and Caicos Islands', 'iso3' => 'TCA', 'numcode' => '796', 'phonecode' => '1649', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'TV', 'country_name' => 'Tuvalu', 'iso3' => 'TUV', 'numcode' => '798', 'phonecode' => '688', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'UG', 'country_name' => 'Uganda', 'iso3' => 'UGA', 'numcode' => '800', 'phonecode' => '256', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'UA', 'country_name' => 'Ukraine', 'iso3' => 'UKR', 'numcode' => '804', 'phonecode' => '380', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'AE', 'country_name' => 'United Arab Emirates', 'iso3' => 'ARE', 'numcode' => '784', 'phonecode' => '971', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'GB', 'country_name' => 'United Kingdom', 'iso3' => 'GBR', 'numcode' => '826', 'phonecode' => '44', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'US', 'country_name' => 'United States', 'iso3' => 'USA', 'numcode' => '840', 'phonecode' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'UM', 'country_name' => 'United States Minor Outlying Islands', 'iso3' => NULL,'numcode' => NULL,'phonecode' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'UY', 'country_name' => 'Uruguay', 'iso3' => 'URY', 'numcode' => '858', 'phonecode' => '598', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'UZ', 'country_name' => 'Uzbekistan', 'iso3' => 'UZB', 'numcode' => '860', 'phonecode' => '998', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'VU', 'country_name' => 'Vanuatu', 'iso3' => 'VUT', 'numcode' => '548', 'phonecode' => '678', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'VE', 'country_name' => 'Venezuela', 'iso3' => 'VEN', 'numcode' => '862', 'phonecode' => '58', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'VN', 'country_name' => 'Viet Nam', 'iso3' => 'VNM', 'numcode' => '704', 'phonecode' => '84', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'VG', 'country_name' => 'Virgin Islands, British', 'iso3' => 'VGB', 'numcode' => '92', 'phonecode' => '1284', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'VI', 'country_name' => 'Virgin Islands, U.S.', 'iso3' => 'VIR', 'numcode' => '850', 'phonecode' => '1340', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'WF', 'country_name' => 'Wallis and Futuna', 'iso3' => 'WLF', 'numcode' => '876', 'phonecode' => '681', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'EH', 'country_name' => 'Western Sahara', 'iso3' => 'ESH', 'numcode' => '732', 'phonecode' => '212', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'YE', 'country_name' => 'Yemen', 'iso3' => 'YEM', 'numcode' => '887', 'phonecode' => '967', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'ZM', 'country_name' => 'Zambia', 'iso3' => 'ZMB', 'numcode' => '894', 'phonecode' => '260', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'ZW', 'country_name' => 'Zimbabwe', 'iso3' => 'ZWE', 'numcode' => '716', 'phonecode' => '263', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'RS', 'country_name' => 'Serbia', 'iso3' => 'SRB', 'numcode' => '688', 'phonecode' => '381', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'ME', 'country_name' => 'Montenegro', 'iso3' => 'MNE', 'numcode' => '499', 'phonecode' => '382', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'AX', 'country_name' => 'Aland Islands', 'iso3' => 'ALA', 'numcode' => '248', 'phonecode' => '358', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'BQ', 'country_name' => 'Bonaire', 'iso3' => 'BES', 'numcode' => '535', 'phonecode' => '599', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'CW', 'country_name' => 'Curacao', 'iso3' => 'CUW', 'numcode' => '531', 'phonecode' => '599', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'GG', 'country_name' => 'Guernsey', 'iso3' => 'GGY', 'numcode' => '831', 'phonecode' => '44', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'IM', 'country_name' => 'Isle of Man', 'iso3' => 'IMN', 'numcode' => '833', 'phonecode' => '44', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'JE', 'country_name' => 'Jersey', 'iso3' => 'JEY', 'numcode' => '832', 'phonecode' => '44', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'XK', 'country_name' => 'Kosovo', 'iso3' => '---', 'numcode' => '0', 'phonecode' => '381', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'BL', 'country_name' => 'Saint Barthelemy', 'iso3' => 'BLM', 'numcode' => '652', 'phonecode' => '590', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'MF', 'country_name' => 'Saint Martin', 'iso3' => 'MAF', 'numcode' => '663', 'phonecode' => '590', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'SX', 'country_name' => 'Sint Maarten', 'iso3' => 'SXM', 'numcode' => '534', 'phonecode' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['iso' => 'SS', 'country_name' => 'South Sudan', 'iso3' => 'SSD', 'numcode' => '728', 'phonecode' => '211', 'created_at' => now(), 'updated_at' => now()]
        ]);

        DB::table('roles')->insert([
            ['role_name' => 'Presenter', 'role_desc' => 'Presenter'],
            ['role_name' => 'Non-Presenter', 'role_desc' => 'Non-Presenter'],
            ['role_name' => 'Abstract Reviewer', 'role_desc' => 'Abstract Reviewer'],
            ['role_name' => 'Paper Reviewer', 'role_desc' => 'Paper Reviewer'],
            ['role_name' => 'Editor', 'role_desc' => 'Editor'],
            ['role_name' => 'Organizer', 'role_desc' => 'Organizer'],
            ['role_name' => 'Admin', 'role_desc' => 'Admin'],
        ]);

        DB::table('users')->insert([
            [
                'username' => 'root',
                'password' => Hash::make('password123', [
                    'memory' => 1024,
                    'time' => 2,
                    'threads' => 2,
                ]),
                'email' => 'submeet.root@gmail.com',
                'given_name' => 'Admin',
                'family_name' => 'Admin',
                'honorif' => 'Mr.',
                'institution_name' => 'Example University',
                'country_id' => 3, // Assuming 'Indonesia' has country_id 3
                'ct_phone_number_1' => '62',
                'ct_phone_number_2' => '62',
                'phone_number_1' => '1234567890',
                'phone_number_2' => '0987654321',
                'root' => true,
                'status' => true,
                'activated_at' => now(),
                'first_login_at' => now(),
                'last_login_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'presenter',
                'password' => Hash::make('password123', [
                    'memory' => 1024,
                    'time' => 2,
                    'threads' => 2,
                ]),
                'email' => 'presenter@mail.com',
                'given_name' => 'Faris',
                'family_name' => 'A',
                'honorif' => 'Mr.',
                'institution_name' => 'Polban',
                'country_id' => 3,
                'ct_phone_number_1' => '62',
                'ct_phone_number_2' => '62',
                'phone_number_1' => '1234567890',
                'phone_number_2' => '0987654321',
                'root' => false,
                'status' => true,
                'activated_at' => now(),
                'first_login_at' => now(),
                'last_login_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'nonpresenter',
                'password' => Hash::make('password123', [
                    'memory' => 1024,
                    'time' => 2,
                    'threads' => 2,
                ]),
                'email' => 'nonpresenter@mail.com',
                'given_name' => 'Thoriq',
                'family_name' => 'Fadhli',
                'honorif' => 'Mr.',
                'institution_name' => 'Polban',
                'country_id' => 3,
                'ct_phone_number_1' => '62',
                'ct_phone_number_2' => '62',
                'phone_number_1' => '1234567890',
                'phone_number_2' => '0987654321',
                'root' => false,
                'status' => true,
                'activated_at' => now(),
                'first_login_at' => now(),
                'last_login_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'editor',
                'password' => Hash::make('password123', [
                    'memory' => 1024,
                    'time' => 2,
                    'threads' => 2,
                ]),
                'email' => 'editor@mail.com',
                'given_name' => 'Editor',
                'family_name' => 'Editor',
                'honorif' => 'Mr.',
                'institution_name' => 'Polban',
                'country_id' => 3,
                'ct_phone_number_1' => '62',
                'ct_phone_number_2' => '62',
                'phone_number_1' => '1234567890',
                'phone_number_2' => '0987654321',
                'root' => false,
                'status' => true,
                'activated_at' => now(),
                'first_login_at' => now(),
                'last_login_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'paper_reviewer',
                'password' => Hash::make('password123', [
                    'memory' => 1024,
                    'time' => 2,
                    'threads' => 2,
                ]),
                'email' => 'paper_reviewer@mail.com',
                'given_name' => 'paper_reviewer',
                'family_name' => 'paper_reviewer',
                'honorif' => 'Mr.',
                'institution_name' => 'Polban',
                'country_id' => 3,
                'ct_phone_number_1' => '62',
                'ct_phone_number_2' => '62',
                'phone_number_1' => '1234567890',
                'phone_number_2' => '0987654321',
                'root' => false,
                'status' => true,
                'activated_at' => now(),
                'first_login_at' => now(),
                'last_login_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'paper_reviewer2',
                'password' => Hash::make('password123', [
                    'memory' => 1024,
                    'time' => 2,
                    'threads' => 2,
                ]),
                'email' => 'paper_reviewer2@mail.com',
                'given_name' => 'paper_reviewer2',
                'family_name' => 'paper_reviewer2',
                'honorif' => 'Mr.',
                'institution_name' => 'Polban',
                'country_id' => 3,
                'ct_phone_number_1' => '62',
                'ct_phone_number_2' => '62',
                'phone_number_1' => '1234567890',
                'phone_number_2' => '0987654321',
                'root' => false,
                'status' => true,
                'activated_at' => now(),
                'first_login_at' => now(),
                'last_login_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'organizer',
                'password' => Hash::make('password123', [
                    'memory' => 1024,
                    'time' => 2,
                    'threads' => 2,
                ]),
                'email' => 'organizer@mail.com',
                'given_name' => 'organizer',
                'family_name' => 'organizer',
                'honorif' => 'Mr.',
                'institution_name' => 'Polban',
                'country_id' => 3,
                'ct_phone_number_1' => '62',
                'ct_phone_number_2' => '62',
                'phone_number_1' => '1234567890',
                'phone_number_2' => '0987654321',
                'root' => false,
                'status' => true,
                'activated_at' => now(),
                'first_login_at' => now(),
                'last_login_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('events')->insert([
            [
                'event_name' => 'Example Conference',
                'event_shortname' => 'excon',
                'event_desc' => 'This is an example conference',
                'event_code' => 'excon',
                'event_logo' => 'example_conference_logo.png',
                'event_url' => 'https://example.com',
                'event_organizer' => 'Example Organizer',
                'country_id' => 3,
                'manager_name' => 'Jane Doe',
                'manager_contact_email' => 'john.doe@example.com',
                'manager_contact_ct' => '62',
                'manager_contact_number' => '1234567890',
                'submission_start' => now(),
                'submission_end' => now()->addDays(30),
                'revision_start' => now()->addDays(31),
                'revision_end' => now()->addDays(60),
                'join_np_start' => now(),
                'join_np_end' => now()->addDays(90),
                'camera_ready_start' => now()->addDays(91),
                'camera_ready_end' => now()->addDays(120),
                'payment_start' => now(),
                'payment_end' => now()->addDays(120),
                'event_start' => now(),
                'event_end' => now()->addDays(120),
                'event_status' => 'Ongoing',
                'event_tz' => '7',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'event_name' => 'Upcoming Conference',
                'event_shortname' => 'upcon',
                'event_desc' => 'This is an upcoming conference',
                'event_code' => 'upcon',
                'event_logo' => 'upcoming_conference_logo.png',
                'event_url' => 'https://upcoming.com',
                'event_organizer' => 'Upcoming Organizer',
                'country_id' => 3,
                'manager_name' => 'Alice Smith',
                'manager_contact_email' => 'alice.smith@upcoming.com',
                'manager_contact_ct' => '62',
                'manager_contact_number' => '1234567891',
                'submission_start' => now()->addDays(10),
                'submission_end' => now()->addDays(40),
                'revision_start' => now()->addDays(41),
                'revision_end' => now()->addDays(70),
                'join_np_start' => now()->addDays(10),
                'join_np_end' => now()->addDays(100),
                'camera_ready_start' => now()->addDays(101),
                'camera_ready_end' => now()->addDays(130),
                'payment_start' => now()->addDays(10),
                'payment_end' => now()->addDays(130),
                'event_start' => now()->addDays(10),
                'event_end' => now()->addDays(130),
                'event_status' => 'Upcoming',
                'event_tz' => '7',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'event_name' => 'Finished Conference',
                'event_shortname' => 'fincon',
                'event_desc' => 'This is a finished conference',
                'event_code' => 'fincon',
                'event_logo' => 'finished_conference_logo.png',
                'event_url' => 'https://finished.com',
                'event_organizer' => 'Finished Organizer',
                'country_id' => 3,
                'manager_name' => 'Bob Johnson',
                'manager_contact_ct' => '62',
                'manager_contact_email' => 'bob.johnson@finished.com',
                'manager_contact_number' => '1234567892',
                'submission_start' => now()->subDays(120),
                'submission_end' => now()->subDays(90),
                'revision_start' => now()->subDays(89),
                'revision_end' => now()->subDays(60),
                'join_np_start' => now()->subDays(120),
                'join_np_end' => now()->subDays(30),
                'camera_ready_start' => now()->subDays(29),
                'camera_ready_end' => now()->subDays(1),
                'payment_start' => now()->subDays(120),
                'payment_end' => now()->subDays(1),
                'event_start' => now()->subDays(120),
                'event_end' => now()->subDays(1),
                'event_status' => 'Finished',
                'event_tz' => '7',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ]
        ]);

        DB::table('users_events')->insert([
            [
                'user_id' => 2,
                'event_id' => 1,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'user_id' => 3,
                'event_id' => 1,
                'role_id' => 2,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'user_id' => 4,
                'event_id' => 1,
                'role_id' => 5,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'user_id' => 5,
                'event_id' => 1,
                'role_id' => 4,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'user_id' => 6,
                'event_id' => 1,
                'role_id' => 4,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'user_id' => 7,
                'event_id' => 1,
                'role_id' => 6,
                'created_at' => now(),
                'updated_at' => now()
            ],
        ]);

        DB::table('topics')->insert([
            ['topic_name' => 'Artificial Intelligence', 'event_id' => 2],
            ['topic_name' => 'Machine Learning', 'event_id' => 2],
            ['topic_name' => 'Data Science', 'event_id' => 2],
            ['topic_name' => 'Cybersecurity', 'event_id' => 2],
            ['topic_name' => 'Cloud Computing', 'event_id' => 2],
            ['topic_name' => 'Internet of Things', 'event_id' => 2],
            ['topic_name' => 'Software Engineering', 'event_id' => 2],
            ['topic_name' => 'Human-Computer Interaction', 'event_id' => 2],
            ['topic_name' => 'Robotics', 'event_id' => 2],
            ['topic_name' => 'Blockchain', 'event_id' => 2],
        ]);

        DB::table('topics')->insert([
            ['topic_name' => 'Artificial Intelligence', 'event_id' => 1],
            ['topic_name' => 'Machine Learning', 'event_id' => 1],
            ['topic_name' => 'Data Science', 'event_id' => 1],
            ['topic_name' => 'Cybersecurity', 'event_id' => 1],
            ['topic_name' => 'Cloud Computing', 'event_id' => 1],
            ['topic_name' => 'Internet of Things', 'event_id' => 1],
            ['topic_name' => 'Software Engineering', 'event_id' => 1],
            ['topic_name' => 'Human-Computer Interaction', 'event_id' => 1],
            ['topic_name' => 'Robotics', 'event_id' => 1],
            ['topic_name' => 'Blockchain', 'event_id' => 1],
        ]);

        DB::table('topics')->insert([
            ['topic_name' => 'Artificial Intelligence', 'event_id' => 3],
            ['topic_name' => 'Machine Learning', 'event_id' => 3],
            ['topic_name' => 'Data Science', 'event_id' => 3],
            ['topic_name' => 'Cybersecurity', 'event_id' => 3],
            ['topic_name' => 'Cloud Computing', 'event_id' => 3],
            ['topic_name' => 'Internet of Things', 'event_id' => 3],
            ['topic_name' => 'Software Engineering', 'event_id' => 3],
            ['topic_name' => 'Human-Computer Interaction', 'event_id' => 3],
            ['topic_name' => 'Robotics', 'event_id' => 3],
            ['topic_name' => 'Blockchain', 'event_id' => 3],
        ]);

        DB::table('review_items')->insert([
            [
                'name' => 'Originality and Significance',
                'desc' => 'How novel and impactful is the research contribution?',
                'weight' => 20,
                'seq' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'event_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Problem Statement and Clarity',
                'desc' => 'Is the research problem clearly stated, well-motivated, and justified?',
                'weight' => 20,
                'seq' => 2,
                'created_by' => 1,
                'updated_by' => 1,
                'event_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Technical Soundness',
                'desc' => 'Are the methods rigorous, valid, and appropriate for the research?',
                'weight' => 20,
                'seq' => 3,
                'created_by' => 1,
                'updated_by' => 1,
                'event_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Results and Analysis',
                'desc' => 'Are the results well-presented, thoroughly analyzed, and supported by evidence?',
                'weight' => 20,
                'seq' => 4,
                'created_by' => 1,
                'updated_by' => 1,
                'event_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Presentation Quality',
                'desc' => 'Is the paper well-written, structured, and visually clear with proper citations?',
                'weight' => 10,
                'seq' => 5,
                'created_by' => 1,
                'updated_by' => 1,
                'event_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Relevance and Audience Engagement',
                'desc' => 'Does the paper align with the conference theme and interest its intended audience?',
                'weight' => 10,
                'seq' => 6,
                'created_by' => 1,
                'updated_by' => 1,
                'event_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ]
        ]);
        DB::table('review_options')->insert([
            // UNTUK ITEM 1
            [
                'review_item_id' => 1,
                'scale' => 1,
                'desc' => 'Very low (commonplace, no novelty)',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'review_item_id' => 1,
                'scale' => 2,
                'desc' => 'Low (minor novelty)',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'review_item_id' => 1,
                'scale' => 3,
                'desc' => 'Moderate (some innovation)',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'review_item_id' => 1,
                'scale' => 4,
                'desc' => 'High (clear and impactful novelty)',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'review_item_id' => 1,
                'scale' => 5,
                'desc' => 'Very high (groundbreaking contribution)',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            // UNTUK ITEM 2
            [
                'review_item_id' => 2,
                'scale' => 1,
                'desc' => 'Very unclear or missing',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'review_item_id' => 2,
                'scale' => 2,
                'desc' => 'Somewhat unclear or inconsistent',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'review_item_id' => 2,
                'scale' => 3,
                'desc' => 'Partially clear and justified',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'review_item_id' => 2,
                'scale' => 4,
                'desc' => 'Mostly clear with strong motivation',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'review_item_id' => 2,
                'scale' => 5,
                'desc' => 'Exceptionally clear and well-justified',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            // UNTUK ITEM 3
            [
                'review_item_id' => 3,
                'scale' => 1,
                'desc' => 'Very flawed or missing',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'review_item_id' => 3,
                'scale' => 2,
                'desc' => 'Somewhat flawed or partially correct',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'review_item_id' => 3,
                'scale' => 3,
                'desc' => 'Basic validity with minor flaws',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'review_item_id' => 3,
                'scale' => 4,
                'desc' => 'Sound methods with minor improvements needed',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'review_item_id' => 3,
                'scale' => 5,
                'desc' => 'Exemplary technical rigor and validity',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            // UNTUK ITEM 4
            [
                'review_item_id' => 4,
                'scale' => 1,
                'desc' => 'Very poor (incomplete or unsupported results)',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'review_item_id' => 4,
                'scale' => 2,
                'desc' => 'Weak (superficial analysis)',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'review_item_id' => 4,
                'scale' => 3,
                'desc' => 'Satisfactory (reasonable analysis)',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'review_item_id' => 4,
                'scale' => 4,
                'desc' => 'Good (comprehensive analysis)',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'review_item_id' => 4,
                'scale' => 5,
                'desc' => 'Excellent (deep insights with flawless evidence)',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            // UNTUK ITEM 5
            [
                'review_item_id' => 5,
                'scale' => 1,
                'desc' => 'Very poor writing and visuals',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'review_item_id' => 5,
                'scale' => 2,
                'desc' => 'Weak (acceptable but needs major improvement',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'review_item_id' => 5,
                'scale' => 3,
                'desc' => 'Average (well-written and organized)',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'review_item_id' => 5,
                'scale' => 4,
                'desc' => 'Good (clear and effective presentation)',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'review_item_id' => 5,
                'scale' => 5,
                'desc' => 'Outstanding (exceptionally clear and professional)',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            // UNTUK ITEM 6
            [
                'review_item_id' => 6,
                'scale' => 1,
                'desc' => 'Very low alignment and engagement',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'review_item_id' => 6,
                'scale' => 2,
                'desc' => 'Low alignment and limited interest',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'review_item_id' => 6,
                'scale' => 3,
                'desc' => 'Moderate alignment and engagement',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'review_item_id' => 6,
                'scale' => 4,
                'desc' => 'High alignment and interest',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'review_item_id' => 6,
                'scale' => 5,
                'desc' => 'Exceptional alignment and strong audience engagement',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            
        ]);

        DB::table('expertises')->insert([
            ['expertise_name' => 'Natural Language Processing'],
            ['expertise_name' => 'Eco-Friendly Technology'],
        ]);
    }
}
